---
title: "submission-requirements"
author: "Joe Dean"
date: "10/15/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    code_folding: hide
    css: mystyle.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Questionnaire (200 words max.)

### Briefly describe the broader goals of your project. (40/40 words)

Barriers to health seeks to give community members and leaders tools to overcome local obstacles in the fight against COVID-19, whether it's attitudes, beliefs, or behaviors.  The hope is to encourage local action and conversation rather than villainize or blame.  

#### What specific problem are you trying to solve for this submission? (36/40 words)



#### Briefly describe your approach. (58/60 words)

We merged survey and census data from c3.ai's data lake with county health data from Robert Wood Johnson Foundation.  We created virus belief profiles using a bespoke Bernoulli mixture model and then used various supervised machine learning techniques and Bayesian statistical modeling to find the drivers of attitudes, beliefs, and behaviors around COVID-19.  We used R, Stan, and C++.     

#### What makes your project unique? (40/40 words)

While many data and analytics projects rightly focus on the spread of the virus, this can be very hard to accurately predict.  This project instead focuses on insights into the one thing we can control--our own attitudes and behaviors.   

#### What is the potential impact of your results in the fight against COVID-19? (20 words)




## Non-Technical Abstract (100 words max.)

While many are doing all they can as individuals to stop the spread of COVID, we must admit there is more progress to be made on this front.  In the face of isolation and online echo chambers, it can be easy to choose stereotypes and shorthand to explain others' attitudes and behaviors.  Surveys, on the other hand, can help ground us in data and understand different perspectives.  Combining these surveys with socio-economic factors and existing social determinants of health data can help us dig deeper into how COVID-19 threatens to amplify existing health disparities around the country.  

## Demo video (60-120 seconds)


## A creative expression of the solution, designed to sell it, while explaining:

Demo your project and the API’s used to run it.
Make sure to explain the problem being solved and walk-through how your solution works.
Touch on your results and the potential impact of these results on COVID-19.

## Source Code (or link to GitHub Repository)

The project repo can be found here: https://github.com/melondonkey/c3pi .

Note this repo was made private for the contest, so the author may need to be reached to unlock the repo.  

## List of Data Sources Used:

From the c3.ai data lake we used:

1. Surveys
2. Locations


In addition, this project also utilizes the County Health Rankings Dataset published by the Robert Wood Johnson Foundation.  https://www.countyhealthrankings.org/sites/default/files/analytic_data2018_0.csv


HUD zip-county crosswalk: https://www.huduser.gov/portal/datasets/usps_crosswalk.html 


At least two datasets used must be from the C3.ai COVID-19 Data Lake.
All datasets must be open-access and links to any external datasets must be provided.